Vagrant.configure("2") do |config|

  # Modern syntax check for the hostmanager plugin
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
  end
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "generic/centos9s"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provider "vmware_desktop" do |v|
      v.memory = "600"
      v.clone_directory = "D:/VagrantVm/db01"
    end
  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "generic/centos9s"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provider "vmware_desktop" do |v|
      v.memory = "600"
      v.clone_directory = "D:/VagrantVm/mc01"
    end
  end
  
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "generic/centos9s"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.13"
    rmq01.vm.provider "vmware_desktop" do |v|
      v.memory = "600"
      v.clone_directory = "D:/VagrantVm/rmq01"
    end
  end
  
### tomcat vm ###
   config.vm.define "app01" do |app01|
    app01.vm.box = "generic/centos9s"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.provider "vmware_desktop" do |v|
      v.memory = "800"
      v.clone_directory = "D:/VagrantVm/app01"
    end
   end
   
### Nginx VM ###
  config.vm.define "web01" do |web01|
    # Changed from ubuntu/jammy64 to the VMware-compatible version
    web01.vm.box = "generic/ubuntu2204"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.provider "vmware_desktop" do |v|
      v.memory = "800"
      v.clone_directory = "D:/VagrantVm/web01"
    end
  end
  
end